# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "dd534989803cfb90286012a6ee4867c7"
name = "fgc-custom-checkout-activeskin"
handle = "fgc-custom-checkout-activeskin-1"
application_url = "https://example.com/"
embedded = true

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
